#!/Users/jonathanchristian/.nvm/versions/node/v16.17.0/bin/node

let fs = require("fs");
let Phrase = require("mhartl-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log("palindrome detected:", line);
  }
});